### ISSUE TITLE
Python error "TypeError: argument of type 'NoneType' is not iterable"

### ISSUE THREAD

**Issue by cebonet** [fsharp/vim-fsharp#33]
I'm getting the following error after installing vim-fsharp using pathogon. 

Error detected while processing /home/cebrail/.vim/bundle/vim-fsharp/ftplugin/fsharp.vim:
line   64:
Traceback (most recent call last):
  File "<string>", line 24, in <module>
  File "<string>", line 22, in get_path
TypeError: argument of type 'NoneType' is not iterable

**Comment by yever** [comment]
What operating system are you using?

**Comment by kjnilsson** [comment]
I've seen this error occasionally when the fsharpautocomplete process has crashed. can you run fsharpautocomple.exe on it's own?

**Comment by alvoha** [comment]
I'm running into this as well with the following error message:
`Error detected while processing /home/alvoha/.vim/bundle/vim-fsharp/ftplugin/fsharp.vim:
line   64:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/alvoha/.vim/bundle/vim-fsharp/ftplugin/fsharpvim.py", line 107, in work
    parsed = json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "<string>", line 24, in <module>
  File "<string>", line 22, in get_path
TypeError: argument of type 'NoneType' is not iterable
`
I'm on Ubuntu 14.04 LTS and installing with pathogen

**Comment by yever** [comment]
When does this error occur? Is it the result of a specific action or nothing works at all?

I'm using Ubuntu 14.04 too with pathogen and I don't seem to encounter it.

**Comment by cebonet** [comment]
After a fresh install I get the same error as alvoha mentions. After running install.sh the errors reduces to:
---
Error detected while processing /home/cebrail/.vim/bundle/vim-fsharp/ftplugin/fsharp.vim:
line 64:
Traceback (most recent call last):
File "", line 24, in 
File "", line 22, in get_path
TypeError: argument of type 'NoneType' is not iterable 
---
The error shows up when opening a .fs file. I'm using 64-bit Arch and I'm able to run the fsharpautocomplete file using mono.

**Comment by t3476** [comment]
This problem is caused by elder python 2.
vim is using python 2 by default on Archlinux.
install the vim with newer python 3
**pacman -S gvim-python3**

**Comment by puffybsd** [comment]
I've encountered the same issue (line 64..."TypeError: argument of 'NoneType' is not iterable"), and was able to "resolve" it this morning.

The problem appears to be a "heisenbug": while adding debug statements to determine why the plugin is attempting to iterate a 'None' value, the issue disappeared.  Turns out there's a variable that gets initialized to an empty map, but reinitialized by G.fsac.get_paths(), which is sometimes returning None.  Adding a call to G.fsac.get_paths() when G.fsac is initialized fixes it.

By the way, I'm running arch as well, but on two systems both running arch linux, one had the issue and another did not.  vim, mono, fsharp, python, all the same.  Same package manager (vim-plug) with the same version. Diffed .vim, env and .vimrc.  Only difference appears to be kernel and architecture (4.4.0/intel vs. 4.2.5/amd).

I've sent a pull request https://github.com/fsharp/vim-fsharp/pull/36

**Comment by puffybsd** [comment]
Incidentally, the machine exhibiting the behavior was able to run the plugin before upgrading to ssd and switching from fedora to arch, so unlikely related to intel vs amd.

Checks are failing on the pull request due to:
"Specify a project or solution file. The directory does not contain a project or solution file."
Not sure what needs to be done here if anything.

**Comment by t3476** [comment]
On Archlinux, It still occurs but installing **gvim-python3** instead of **gvim** solves the problem.

**Comment by xqguo** [comment]
This is due to get_paths function. i fixed it and created a pull request.
